# Requirements

In [1]:
import numpy as np

# Aggregation over 2D array

Create a $4 \times 6$ array.

In [ ]:
A = np.arange(24).reshape(4, -1)
A

Sum over the elements of the columns.

In [4]:
A.sum(axis=0)

array([36, 40, 44, 48, 52, 56])

Sum over the elements of the rows.

In [5]:
A.sum(axis=1)

array([ 15,  51,  87, 123])

Sum over all elements of the array.

In [6]:
A.sum()

np.int64(276)

# Aggregation over 3D array

Create a $2 \times 3 \times 4$ array.

In [12]:
B = A.reshape(2, 3, -1)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Sum over axis 0, the result is a $3 \times 4$ array.

In [8]:
B.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Sum over axis 0 and 1, the result is an array with 4 elements.

In [10]:
B.sum(axis=(0, 1))

array([60, 66, 72, 78])

Sum over axis 0 and 2, the result is an array with 3 elements.

In [11]:
B.sum(axis=(0, 2))

array([ 60,  92, 124])

The axis apply to other aggregation functions such as `np.min`, `np.max`, `np.prod` and so on.