# Requirements

In [1]:
import numpy as np

# Aggregation functions

## Aggregation over 2D array

Create a $4 \times 6$ array.

In [2]:
A = np.arange(24).reshape(4, -1)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Sum over the elements of the columns.

In [3]:
A.sum(axis=0)

array([36, 40, 44, 48, 52, 56])

Sum over the elements of the rows.

In [4]:
A.sum(axis=1)

array([ 15,  51,  87, 123])

Sum over all elements of the array.

In [5]:
A.sum()

np.int64(276)

## Aggregation over 3D array

Create a $2 \times 3 \times 4$ array.

In [6]:
B = A.reshape(2, 3, -1)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Sum over axis 0, the result is a $3 \times 4$ array.

In [7]:
B.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Sum over axis 0 and 1, the result is an array with 4 elements.

In [8]:
B.sum(axis=(0, 1))

array([60, 66, 72, 78])

Sum over axis 0 and 2, the result is an array with 3 elements.

In [9]:
B.sum(axis=(0, 2))

array([ 60,  92, 124])

The axis apply to other aggregation functions such as `np.min`, `np.max`, `np.prod` and so on.

# Transpose

For multi-dimensional arrays, the `np.transpose` function can transpose over arbitrary axes.

In [10]:
C = np.arange(24).reshape(2, 3, -1)

In [11]:
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

By default, the first and last axis are swapped.

In [12]:
np.transpose(C)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [13]:
assert(np.allclose(
    C.transpose(),
    np.einsum('ijk -> kji', C)
))

However, you can swap any axes by specifying a tuple.

In [14]:
np.transpose(C, axes=(1, 2, 0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [15]:
assert(np.allclose(
    np.transpose(C, axes=(1, 0, 2)),
    np.einsum('ijk -> jik', C)
))

Note that no data is moved during a transpose.

In [16]:
assert(
    C.base is np.transpose(C, axes=(2, 0, 1)).base
)

If you want to swap two axes, you can do so using `np.swapaxes`.

In [17]:
assert(np.allclose(
    np.transpose(C, axes=(1, 0, 2)),
    np.swapaxes(C, 0, 1)
))