# Array indexing

In [1]:
import numpy as np

## ellipsis

Create a 2 by 3 by 4 array with consecutive numbers.

In [3]:
A = np.arange(0.0, 23.5, 1.0).reshape((2, 3, 4))

2D subarrays can be selected by specifying an index for a single dimension, while representing the others with an ellipsis.

In [4]:
A[..., 0]

array([[ 0.,  4.,  8.],
       [12., 16., 20.]])

In [5]:
A[0, ...]

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

# `np.newaxis`

Create a 400 by 500 of random numbers.  The array should subsequently be normalized along the rows.

In [24]:
A = np.random.uniform(size=(400, 500))

The normalization could be donw in an iteration over the rows.

In [28]:
%%timeit
B = np.empty_like(A)
for row in range(A.shape[0]):
    B[i, :] = A[i, :]/A[i, :].sum()

3.31 ms ± 518 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Verify that `B` is normalized.

In [29]:
B.sum(axis=1).min(), B.sum(axis=1).max()

(0.9999999999999998, 1.0000000000000002)

A somewhat faster alternative would be the following code.

In [30]:
%%timeit
B = np.empty_like(A)
for i, total in enumerate(A.sum(axis=1)):
    B[i, :] = A[i, :]/total

2.6 ms ± 373 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
B.sum(axis=1).min(), B.sum(axis=1).max()

(0.9999999999999998, 1.0000000000000002)

However, using broadcasting would be most efficient.  For this to work the array containing the sums of the rows must be a 2D array, which can be created from the original using `np.newaxis`.

In [32]:
%%timeit
B = A/A.sum(axis=1)[..., np.newaxis]

886 µs ± 47.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
B.sum(axis=1).min(), B.sum(axis=1).max()

(0.9999999999999998, 1.0000000000000002)

## Integer indexing

Consider a 4 by 6 2D array.

In [35]:
A = np.arange(0.0, 23.5, 1.0).reshape((4, -1))

In [37]:
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

We can select elements in this 2D array using lists of indices for each dimension.

In [40]:
i0, i1 = [0, 1, 2, 1, 0], [0, 1, 2, 3, 4]

In [41]:
A[i0, i1]

array([ 0.,  7., 14.,  9.,  4.])

## Boolean indexing

Consider a 4 by 6 2D array.

In [35]:
A = np.arange(0.0, 23.5, 1.0).reshape((4, -1))

In [45]:
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

Evaluating a Boolean condidtion taht involves an numpy array yields a Boolean array with the same shape.

In [46]:
i = A > 8.0

In [47]:
i

array([[False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

This array can be used to index an array of the same shape, e.g., `A`.

In [48]:
A[i]

array([ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.,
       22., 23.])

Note that the shape and even the number of dimensions of the resulting array is not necessarily that of the original array.