# Numpy experiments

Import numpy package.

In [1]:
import numpy as np

## Reshaping

Optionally, the last index given in `reshape` can be `-1`, the shape will be such that the dimensions multiply to the size of the original array.

In [2]:
a = np.arange(1, 21, dtype=np.int32).reshape(4, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)

In three dimensions, the last dimension can be replaced by `-1`.

In [3]:
b = a.reshape(2, 5, -1)
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]], dtype=int32)

## Slicing

Define 3D data with a "width" of 5, a "height" of 4, and a "depth" of 3.

In [4]:
a = np.arange(1, 61, dtype=np.int32).reshape((3, 4, -1))

When the last dimension is -1, it is computed automatically if possible, i.e., if the product of the sizes in each dimension is the size of the array.

In [5]:
a.shape

(3, 4, 5)

When data is viewed as 3D, slice the "front" layer.

In [6]:
a[0, :, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)

Equivalently, the ellipsis `...` can be used to range over the two remaining dimensions when the first is fixed.  This can be very useful if the rank of the matrix is not known a priori.

In [7]:
a[0, ...]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)

Slice the middle layer.

In [8]:
a[1, :, :]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]], dtype=int32)

Slice the back layer.

In [9]:
a[2, :, :]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]], dtype=int32)

Slice the top layer (first row is front).

In [10]:
a[:, 0, :]

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [41, 42, 43, 44, 45]], dtype=int32)

Slice the left layer (first row is front).

In [11]:
a[:, :, 0]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]], dtype=int32)

Introducing new leading dimension.

In [12]:
a[None].shape

(1, 3, 4, 5)

Check that this is the original matrix, with size of leading dimension equal to 1.

In [13]:
np.all(a == a[None][0])

np.True_

Add additional "last" dimension, check that the result is the top-front row, with each element in an individual dimension 1 subarray.

In [14]:
a[:, :, :, None][0, 0]

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int32)

It is important to realize that slicing doesn't copy, i.e., a slice yields a reference to the original data. Consider the following matrix.

In [15]:
b = np.arange(1, 21).reshape(4, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
c = b[1:-1, 1:-1]
c

array([[ 7,  8,  9],
       [12, 13, 14]])

Now we modify an element of `c`

In [17]:
c[0, 0] = 0
c

array([[ 0,  8,  9],
       [12, 13, 14]])

Clearly, `c` was changed, but so is `b`.

In [18]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Fancy indexing

Create a new $4 \times 5$ array.

In [19]:
a = np.arange(1, 21, dtype=np.int32).reshape((4, -1))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)

Select the second and fourth row.

In [20]:
a[[1, 3], :]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]], dtype=int32)

Select the first and fourth column.

In [21]:
a[:, [0, 3]]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19]], dtype=int32)

## Structured arrays

Although strictly speaking not fancy indexing, we can create structured arrays, which you can think of as arrrays of structures. These arrays can be indexed by number, and by structure field name.

In [22]:
b = np.zeros(10, dtype=[
    ('x', np.float64),
    ('y', np.float64),
])
b

array([(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.),
       (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
      dtype=[('x', '<f8'), ('y', '<f8')])

Each element acts as a tuple, the first field has name `x` and type `np.float64`, the second has name `y`, and is also `np.float64`.

The shape shows it is an 1-D array.

In [23]:
b.shape

(10,)

The type of the elements is perhaps a bit surprising.

In [24]:
type(b[0])

numpy.void

We can initialize the `x` and `y` fields of each array element with a single assingment.

In [25]:
rng = np.random.default_rng(seed=1234)

In [26]:
b['x'] = rng.uniform(size=10)
b['y'] = rng.uniform(size=10)
b

array([(0.97669977, 0.44100612), (0.38019574, 0.60987081),
       (0.92324623, 0.8636213 ), (0.26169242, 0.86375767),
       (0.31909706, 0.67488131), (0.11809123, 0.65987435),
       (0.24176629, 0.7357577 ), (0.31853393, 0.22275366),
       (0.96407925, 0.17206618), (0.2636498 , 0.87041497)],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [27]:
b['x']

array([0.97669977, 0.38019574, 0.92324623, 0.26169242, 0.31909706,
       0.11809123, 0.24176629, 0.31853393, 0.96407925, 0.2636498 ])

Using a numerical index gives the corresponding element in the array.

In [28]:
b[0]

np.void((0.9766997666981422, 0.4410061220535114), dtype=[('x', '<f8'), ('y', '<f8')])

Accessing elements by field number or field name is equivalent.

In [29]:
b[4][1] == b[4]['y']

np.True_

Note that using structured arrays can hurt performance since vectorization is often not possible due the the underlying data structure.

## Stacking

Create two matrices, both $4 \times 5$.

In [30]:
a = np.arange(1, 21, dtype=np.int32).reshape((4, -1))
b = np.arange(21, 41, dtype=np.int32).reshape((4, -1))
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


Stack matrices horizontally.

In [31]:
np.hstack((a, b))

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35],
       [16, 17, 18, 19, 20, 36, 37, 38, 39, 40]], dtype=int32)

Stack matrices vertically.

In [32]:
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]], dtype=int32)

Create a list of 3 arrays, each $4 \times 5$.

In [33]:
arrays_2d = []
size_2d = 20
for i in range(3):
    upperleft = i*size_2d + 1
    arrays_2d.append(np.arange(upperleft, upperleft + size_2d, dtype=np.int32).reshape(4, -1))

Create a 3D array out of the list of 2D arrays.

In [34]:
array_3d = np.array(arrays_2d)

array_3d.shape

(3, 4, 5)

Get front plane.

In [35]:
array_3d[0, :, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)

Get top plane.

In [36]:
array_3d[:, 0, :]

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25],
       [41, 42, 43, 44, 45]], dtype=int32)