# Requirements

In [1]:
import numpy as np

In [15]:
rng = np.random.default_rng(seed=1234)

# Operations

Create a square matrix.

In [22]:
A = np.arange(16.0).reshape(4, -1)
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

Many (bassic) linear algebra operations are defined in numpy's `np.linalg` module.

## Trace

The trace, i.e., the sum of the diagonal elements, can be computed using `np.linalg.trace`.

In [23]:
np.linalg.trace(A)

np.float64(30.0)

In [24]:
assert(np.isclose(
    np.linalg.trace(A),
    np.einsum('ii ->', A)
))

Note: `np.trace` can also be used for 2D matrices, however, for $n$-dimension arrays with $n > 2$, `np.trace` and `np.linalg.trace` have different semantics..

## Transpose

To transpose a matrix, the `np.linalg.matrix_transpose` function can be used.

In [25]:
np.linalg.matrix_transpose(A)

array([[ 0.,  4.,  8., 12.],
       [ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.]])

Note: `np.transpose` can also be used for 2D matrices, however, for $n$-dimension arrays with $n > 2$, `np.transpose` and `np.linalg.transpose` have different semantics..

## Matrix power

The power operator `**` computes an array of hich each element is the power of the original array.

In [3]:
A**3

array([[0.000e+00, 1.000e+00, 8.000e+00, 2.700e+01],
       [6.400e+01, 1.250e+02, 2.160e+02, 3.430e+02],
       [5.120e+02, 7.290e+02, 1.000e+03, 1.331e+03],
       [1.728e+03, 2.197e+03, 2.744e+03, 3.375e+03]])

To compute $A^3$, you have to use the `np.linalg.matrix_power` function.

In [4]:
np.linalg.matrix_power(A, 3)

array([[ 1680.,  1940.,  2200.,  2460.],
       [ 4880.,  5620.,  6360.,  7100.],
       [ 8080.,  9300., 10520., 11740.],
       [11280., 12980., 14680., 16380.]])

In [7]:
assert(np.allclose(
    np.linalg.matrix_power(A, 3),
    A@A@A
))

## Determinant

Computing the determinant is straightforard.

In [9]:
np.linalg.det(A)

np.float64(0.0)

## Linear equations

Define an array `b` representing the right-hand side of the set of equations $A x = b$.

In [16]:
A = rng.uniform(-1.0, 1.0, size=(4, 4))

In [17]:
b = np.linspace(-1.0, 2.0, 4)

Now the values of $x$ can be determined using `np.linalg.solve`.

In [19]:
x = np.linalg.solve(A, b)
x

array([ 3.02819008,  3.68539792, -5.33833152, -3.1783194 ])

In [20]:
assert(np.allclose(
    A@x - b,
    0.0
))

## Matrix inverse

You can invert a matrix using `np.linalg.inv`.

In [26]:
A = rng.uniform(-1.0, 1.0, size=(4, 4))

In [28]:
np.linalg.inv(A)

array([[-0.40891274,  1.0003984 , -1.16907793, -1.05099835],
       [-0.51528758,  1.08891128, -0.20555518, -1.02650448],
       [-0.82050135,  2.67219797, -2.01095371, -0.97469121],
       [ 0.49801602,  2.54403626, -1.19009775, -0.96229336]])

In [29]:
assert(np.allclose(
    A@np.linalg.inv(A),
    np.eye(A.shape[0])
))

## Eigen values and Eigen vectors

In [30]:
A = rng.uniform(-1.0, 1.0, size=(4, 4))

In [32]:
result = np.linalg.eig(A)

In [34]:
result.eigenvalues

array([ 1.2439656 +1.02310828j,  1.2439656 -1.02310828j,
       -0.37843414+0.j        , -0.05411138+0.j        ])

In [35]:
result.eigenvectors

array([[ 0.61971261+0.j        ,  0.61971261-0.j        ,
        -0.51607395+0.j        ,  0.32033053+0.j        ],
       [ 0.26439771+0.4570154j ,  0.26439771-0.4570154j ,
        -0.48593734+0.j        ,  0.6790145 +0.j        ],
       [-0.04456773-0.51983973j, -0.04456773+0.51983973j,
        -0.38871641+0.j        ,  0.5497188 +0.j        ],
       [ 0.22809009-0.11376443j,  0.22809009+0.11376443j,
         0.58858485+0.j        , -0.36624704+0.j        ]])